### PR TITLE
tex is stopped by error

### PR DESCRIPTION
**Pull request by nari0072**
すいません，以下のエラーが出ます．

(./jlisting.sty)
(./boundary_narita.aux)
 ./boundary_narita.tex:46: Undefined control sequence.
<recently read> \1
 l.46 \maketitle
 ?

### CODE REVIEW

**Comment by daddygongon** [comment]
通るよ．全エラーを見せてください．

This is ptex2pdf[.lua] version 0.9.
Processing boundary_narita.tex
This is e-pTeX, Version 3.14159265-p3.7-160201-2.6 (utf8.euc) (TeX Live 2016) (preloaded format=platex)
 restricted \write18 enabled.
entering extended mode
(./boundary_narita.tex
pLaTeX2e <2016/11/29> (based on LaTeX2e <2017/01/01>)
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
(/usr/local/texlive/2016/texmf-dist/tex/platex/jsclasses/jsarticle.cls
Document Class: jsarticle 2017/01/13 okumura, texjporg
(/usr/local/texlive/2016/texmf-dist/tex/platex/jsclasses/jslogo.sty))
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-def/dvipdfmx.def)))
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/local/texlive/2016/texmf-dist/tex/latex/graphics/dvipsnam.def))
(/usr/local/texlive/2016/texmf-dist/tex/latex/url/url.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/listings.sty
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/lstmisc.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/listings.cfg))
(./jlisting.sty) (./boundary_narita.aux (./introduction.aux

LaTeX Warning: Label `default' multiply defined.

) (./method.aux

LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.

) (./codes.aux

LaTeX Warning: Label `default' multiply defined.

) (./results_and_discussions.aux

LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.


LaTeX Warning: Label `default' multiply defined.

) (./conclusion.aux) (./reference.aux)) (./boundary_narita.toc [1]) [2]
[3] (./introduction.tex <../figs/./boundary_narita.002.jpeg> [4]
<../figs/./boundary_narita.004.jpeg>) [5] [6] (./method.tex
(/usr/local/texlive/2016/texmf-dist/tex/latex/base/omscmr.fd)
<../figs/./boundary_narita.006.jpeg> <../figs/./boundary_narita.007.jpeg>
<../figs/./boundary_narita.005.jpeg> [7] [8]) [9] [10] (./codes.tex
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/lstlang1.sty)
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/lstlang2.sty) [11]
[12] [13] [14] [15] [16] [17] <../figs/./boundary_narita.009.jpeg>) [18]
(./results_and_discussions.tex
(/usr/local/texlive/2016/texmf-dist/tex/latex/listings/lstlang1.sty)
<../figs/./boundary_narita.010.jpeg> <../figs/./boundary_narita.011.jpeg>
[19] [20] <../figs/./boundary_narita.012.jpeg>
<../figs/./boundary_narita.013.jpeg> [21] <../figs/./boundary_narita.014.jpeg>
<../figs/./boundary_narita.015.jpeg> [22] <../figs/./boundary_narita.016.jpeg>)
 [23] [24] [25] [26] (./conclusion.tex) [27] (./reference.tex
Underfull \hbox (badness 5563) in paragraph at lines 9--10
\OT1/cmtt/m/n/10 yiiframework . com / doc / guide / 1 . 1 / ja / basics . best-
[]practices,[]$ \OT1/cmr/m/n/10 2017/2/11

Underfull \hbox (badness 1033) in paragraph at lines 12--13
[]\JY1/mc/m/n/10 三面図 \OT1/cmr/m/n/10 (\JY1/mc/m/n/10 機械設計のための基礎製
図\OT1/cmr/m/n/10 ), \JY1/mc/m/n/10 独立行政法人 海上技術安全研究
) [28] (./boundary_narita.aux (./introduction.aux) (./method.aux) (./codes.aux)
 (./results_and_discussions.aux) (./conclusion.aux) (./reference.aux))

LaTeX Warning: There were multiply-defined labels.

 )
(see the transcript file for additional information)
Output written on boundary_narita.dvi (28 pages, 85572 bytes).
SyncTeX written on boundary_narita.synctex.gz.
Transcript written on boundary_narita.log.
boundary_narita.dvi -> boundary_narita.pdf
[1][2][3][4][5][6][7][8][9][10][11][12][13][14][15][16][17][18][19][20][21][22][23][24][25][26][27][28]
1536666 bytes written
boundary_narita.pdf generated by dvipdfmx.

**Comment by nari0072** [comment]
タイプセットによるエラー表示がコピペできないので，スクリーンショットを添付しました．

**Comment by daddygongon** [comment]
ううん．わからんな．こっちでできあがったpdfを使いましょう．figs/boundary_narita.pdfとしています．
なんか変更した？

**Comment by daddygongon** [comment]
エラーが出た後に，hを押すとさらに詳細なエラーが表示されます．
TeXShopを最新版にあげてみるというのも手です．私のとこでは，3.77になっています．

**Comment by nari0072** [comment]
すいません，お願いします．
いいえ，変更してません．git pull直後にtexが動かなくなりました．
論文に概要と謝辞を追加する予定でした．
TeXShopの最新版をインストールしています．
hで以下のエラー詳細が出ました．

**Comment by daddygongon** [comment]
では，概要と謝辞を送ってください．でも，もう寝るよ．
明日早いし．

**Comment by daddygongon** [comment]
あと15分やな．

**Pull request merged**
